pms/urls.py
from django.contrib import admin
from django.urls import path

from party import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<slug:slug>', views.PartyDetailView.as_view(), name="party-detail"),
    path('<int:compo_pk>/submit/', views.SubmitToCompoView.as_view(), name="submit")
]

party/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone


class Party(models.Model):
    title = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    submission_deadline = models.DateTimeField()
    slug = models.SlugField(blank=True)

    @property
    def open_for_submissions(self):
        return timezone.now() <= self.submission_deadline

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Compo(models.Model):
    title = models.CharField(max_length=255)
    party = models.ForeignKey(Party, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['title', 'party']

    def __str__(self):
        return f"{self.party} - {self.title}"


class Submission(models.Model):
    title = models.CharField(max_length=255)
    sub_file = models.FileField(upload_to="uploads/", blank=True)
    thumbnail = models.FileField(upload_to="uploads/", blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField()
    compo = models.ForeignKey(Compo, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.author} - {self.title} - {self.compo}"

party/forms.py
from django.forms import ModelForm, HiddenInput

from party.models import Submission


class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        fields = [
            'title',
            'sub_file',
            'thumbnail',
            'author',
            'description',
            'compo',
        ]
        widgets = {
            'compo': HiddenInput
        }

party/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView  #, ListView
from django.views.generic.edit import CreateView
from django.urls import reverse

from party.models import Compo, Party, Submission
from party.forms import SubmissionForm


class PartyDetailView(DetailView):
    model = Party 
    template_name = 'party/party_detail.html'

"""
class PartyListView(ListView):
    template_name = 'party/party_list.html'

"""

class SubmitToCompoView(CreateView):
    model = Submission
    template_name = 'party/submission_create.html'
    form_class = SubmissionForm

    def get_initial(self):
        initial = super().get_initial()
        initial["compo"] = get_object_or_404(Compo, pk=self.kwargs["compo_pk"])
        return initial

    def form_valid(self, form):
        submission = form.save(commit=False)

        submission.save()
        return HttpResponseRedirect(reverse('party-detail', kwargs={'slug': submission.compo.party.slug }))
    

party/templates/party/party_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ party.title }}</h1>
    <p>{{ party.submission_deadline }}</p>

    <div>
        {% for compo in party.compo_set.all %}
            {{ compo.title }}
            {% if party.open_for_submissions %}
                <a href="{% url 'submit' compo_pk=compo.pk %}">Submit to compo</a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

party/templates/party/submission_create.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DOT PMS</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>